name: Package and Publish

on:
  push:
    tags:
      - 'v*'   # any tag that begins with "v"
    
jobs:
  release:
    runs-on: ubuntu-latest
    environment: Default
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: CurseForge Packager
      uses: BigWigsMods/packager@v2
      env:
        CF_API_KEY: ${{ secrets.CURSEFORGE_API_TOKEN }}
      with:
        args: -g retail
    - name: Create Package
      uses: BigWigsMods/packager@v2
      env:
        CF_API_KEY: ${{ secrets.CURSEFORGE_API_TOKEN }}
      with:
        args: -g retail
